### ISSUE TITLE
Cooking steps

### ISSUE THREAD

**Issue by fleur0121** [yunahu/FlexyCook#27]
Integrate todoist API

**Comment by mgao08** [comment]
Requires styling fix for cooking step cards (about images)

Things to be adjusted:
- [ ] Max-height for pictures
- [ ] Make pictures smaller
- [ ] Enlarge the font size to:
   - [ ] Make instruction more visible
   - [ ] Make the step number larger
   - [ ] Make the equipment & ingredients more extinguishable
